### ISSUE TITLE
Spawn rejects on stderr

### ISSUE THREAD

**Issue by damiankoper** [sanketbajoria/ssh2-promise#65]
I wonder why change in commit https://github.com/sanketbajoria/ssh2-promise/commit/2fc2ce2715d393ad6d891434d1d9b86e5cac9091 was made to `src/sshConnection.ts` file.
My command writes to `stderr` within the first 500ms, so the whole spawned process fails, which should not happen.

I think that lines:
```ts
.stderr.on('data', function (data) {
    reject(data.toString());
});
setTimeout(() => {
    resolve(stream);
}, 500);
```
should be reversed and eventual hopping error (as the commit name suggests) should be handled differently. What do you think?

**Comment by sanketbajoria** [comment]
@damiankoper hmm.. actually it was done so that, when we do connection hopping, we can propagate error properly. 
![image](https://user-images.githubusercontent.com/2969587/130626835-9c0ab658-83e0-4573-82be-fedefa50a608.png)

But, it make sense, if we handle connection hopping logic separately, and i should resolve stream as soon as possible, so now, it will caller responsibility to do error handling from resolved stream object.  
Will do the changes by today

**Comment by sanketbajoria** [comment]
@damiankoper please refer to this commit https://github.com/sanketbajoria/ssh2-promise/commit/b8aebe5cf5abbe4101bee674214041aef46eac9c

Can you please confirm, if it fixes your problem.

**Comment by sanketbajoria** [comment]
@damiankoper 
ssh2-promise@1.0.1 has been published.
